### ISSUE TITLE
Inversion with multiple parameters

### ISSUE THREAD

**Issue by ghost** [gimli-org/transform2021#4]
Hello,
I am interesting of applying the example in "Inversion with any forward operator" for my problem. However, I am wondring if there is the possibility to have more than one parameter in the forward operator, such as OUTPUT = f(param1, param2, depth)? While doing this, I couldn't give a acceptable startModel. Is there a acceptable format for startModel or the forward operator can have only one parameter ?
Thank you in advance for the answer.

**Comment by halbmy** [comment]
The forward operator `f(model)` takes a model vector of arbitrary length, in your case 3. For layered models with `n` layers the length is `2n-1` like in the mentioned example.
